OCR
deepvk/vitrina pull request #8
Opened 2023-01-19 20:12 UTC by dkadochnikov

OCR head with temporary regular expressions (yet only works with lowercase cyrillic and numbers)

2023-01-20 11:47 UTC, SpirinEgor requested changes
There are a lot of changes based on `if ocr_flag`. And most of them because you change what model returns.
I suggest changing the model output to the dict `{"logits": result}`. And in the case of OCR add in it `"ctc_loss": ctc_loss`. Thus, in most cases, you will use logits. And only need to add this small `if`:
```python
if ocr_flag:
    log_dict["bce_loss"] = loss
    log_dict["ctc_loss"] = model_output["ctc_loss"]
    loss = loss + alpha * model_output["ctc_loss"]
log_dict["loss"] = loss
```

Also, I don't like that your model also computes ctc loss. CE computes in one place and CTC in another. What if `VTRClassifier` would return visual embeddings along with logits? And in the train loop, you will use them to compute CTC loss.
```python
bce_loss = criterion(model_output["logits"], batch["labels"])
ctc_loss = compute_ctc_loss(model_output["vtr"], batch["texts"])
```

2023-01-20 11:47 UTC, SpirinEgor commented on src/models/vtr/classifier.py
> +        self.ocr = BiLSTM(input_size=256, hidden_size=256, num_layers=2, num_classes=60)
Let's not hard-code all these numbers, add them to class parameters in any form so in the future we can easily change them.

2023-01-20 11:47 UTC, SpirinEgor commented on src/models/vtr/embedder.py
> +        return self.linear_bridge(batched_conv), conv  # [batch size, slice count, emb size]
Add to the comment shape of `conv`, please

2023-01-20 11:47 UTC, SpirinEgor commented on src/models/vtr/ocr.py
> +class BiLSTM(nn.Module):
Let's call this `OCRHead` to not confuse with regular LSTM layer

2023-01-20 11:47 UTC, SpirinEgor commented on src/utils/train.py
> -    result = {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1_score}
This change is unnecessary 🙃

2023-01-22 11:46 UTC, SpirinEgor commented on src/datasets/vtr_dataset.py
> +            self.labeled_texts.append({"text": clean_text(sample["text"]), "label": sample["label"]})
I suggest checking if the cleaned text is empty and skipping such examples. At the end of init, you can log how many samples you got from the data.

2023-01-22 11:46 UTC, SpirinEgor commented on src/datasets/vtr_dataset.py
> +            self.char_set = set.union(self.char_set, set(self.labeled_texts[-1]["text"]))
```python
self.char_set |= some_string
```

2023-01-22 11:46 UTC, SpirinEgor commented on src/datasets/vtr_dataset.py
> +            self.labeled_texts.append({"text": clean_text(sample["text"]), "label": sample["label"]})
Also, I think using 2 lists for texts and labels would be more convenient for future using

2023-01-22 11:46 UTC, SpirinEgor commented on src/models/vtr/classifier.py
> +            result["ocr logits"] = self.ocr(conv)
It is not good to use spaces in such keys, it may affect in the future somewhere. Just replace them with `_`.

2023-01-22 11:46 UTC, SpirinEgor commented on src/utils/common.py
> +_REG = re.compile("[^а-я0-9 ]", flags=re.MULTILINE)
Do we still need this?

2023-01-25 08:53 UTC, SpirinEgor reviewed
Nice work, thank you for this implementation! Just resolve merging conflicts and maybe add progress bar in dataset init and work is done ✅

2023-01-25 08:53 UTC, SpirinEgor commented on src/datasets/vtr_dataset.py
> +        for sample in labeled_texts:
How fast is this operation? We can add `tqdm` here for better UX 😅

2023-01-25 14:17 UTC, borisshapa reviewed
Good job! Clean and understandable code!

2023-01-25 14:17 UTC, borisshapa commented on src/utils/common.py
> +    targets = torch.LongTensor([char2int_dict[c] for c in text])
Blank label must be 0, so you add 1 to all char ids.
But if you have blank symbol in the char set, there'll be two labels for blank symbol.

2023-01-25 14:17 UTC, borisshapa commented on src/utils/train.py
> +def compute_ctc_loss(criterion: torch.nn.modules.loss.CTCLoss, logits: torch.Tensor, texts: list, char_set: set):
After the order of the dimensions above changes, they will need to be changed in this function as well. Keep in mind that the loss has no option `batch_first`. https://pytorch.org/docs/stable/generated/torch.nn.CTCLoss.html

The loss function takes a tensor of size (T, N, C) or (T, C) where T = sequence length, N = batch size, C = num classes.

Double check that the prediction tensors are correctly related to the ground truth texts

2023-02-03 13:14 UTC, SpirinEgor approved these changes

2023-02-03 13:15 UTC, merged